//this is the main file from which the game  is run

//requiring the inquirer and chalk packages
var inquirer = require('inquirer');
var chalk = require('chalk');

//requiring bank.js to get the random word generated by the computer
var computerChoice = require('./bank.js');
// console.log(computerChoice);

//requiring the word file
var Word = require("./word.js");

//checking if the word gets split
var individualLetterArray = computerChoice.split("");
console.log("TEST array:" + individualLetterArray);

//global variable that can be accessed later
var checkedLetterIndex;

//creating an empty array that will hold the letters that have been guessed already
var correctGuesses = [];

//keeping track of number of guesses
var guessesLeft = 10;


//function to start the game
function playGame() {

	//prompting the user to select a letter
	inquirer.prompt([
	{
	type: "input",
	name: "guess",
	message: " Guess a letter!"
	},
	]).then(answers => {

	//checking if inquirer and chalk packages function
	// console.log(chalk.cyan(answers.guess + "\n"));

			
		//this function will find the index of each letter in the split word and find the index of the user guess against it
		function checkLetter() {
			checkedLetterIndex = individualLetterArray.indexOf(answers.guess);
			console.log(checkedLetterIndex);
		}

		//calling the function
		checkLetter();

		//checking if it the letters match. An index of -1 indicates that the letter was not found
		if (checkedLetterIndex === -1) {


			console.log(chalk.red("\n---------\n" + "INCORRECT!\n" + "---------"));
			console.log("Try again!\n");

			//decrements the number of guesses
			guessesLeft--;
			console.log("Guesses Remaining: " + guessesLeft);

			//if statement to end game when the guesses reach 0
			if (guessesLeft === 0) {

				//logs the following message
				console.log(chalk.bgRed("\n------------------\n" + "    YOU LOSE!     \n" + "------------------\n"));
			}

			//runs the function again, so user can choose another letter
			playGame();
			
		}

		else {

			console.log(chalk.green("\n---------\n" + "CORRECT!\n" + "---------"));

			//pushing correctly guessed letter into the empty array
			correctGuesses.push(answers.guess);
			//checking if array is being populated
			console.log(correctGuesses);
			//removing the correct letter from the individualLetterArray

			//showing the number of guesses left
			console.log("Guesses remaining: " + guessesLeft);

			//runs the function again, so user can choose another letter
			playGame();

		}

	});
}

//this will run the moment the user nodes the file (starts the game)
playGame();


 


