//this is the main file from which the game  is run

//requiring the inquirer and chalk packages
var inquirer = require('inquirer');
var chalk = require('chalk');

//requiring bank.js to get the random word generated by the computer
var computerChoice = require('./bank.js');
// console.log(computerChoice);

//requiring the word file
var Word = require("./word.js");

//checking if the word gets split
var individualLetterArray = computerChoice.split("");
console.log("TEST array:" + individualLetterArray);

//setting a variable that will determine whether the letter is displayed or not
var displayLetter = false;

//new array to hold blanks and correct letter
var blanksAndLetters = [];

//this will loop through the array
for (var j = 0; j < individualLetterArray.length; j++) {

	blanksAndLetters.push("_");

}

//logging the blanks
console.log("blanksAndLetters Array: " + blanksAndLetters);

//global variable that can be accessed later
var checkedLetterIndex;

//creating an empty array that will hold the letters that have been guessed already
var correctGuesses = [];

//keeping track of number of guesses
var guessesLeft = 10;

//the reset game function

//function to start the game, this is for the selected word only
function playGame() {

	//prompting the user to select a letter
	inquirer.prompt([
	{
	type: "input",
	name: "guess",
	message: " Guess a letter!"
	},
	]).then(answers => {

	//checking if inquirer and chalk packages function
	// console.log(chalk.cyan(answers.guess + "\n"));
			
		//this function will find the index of each letter in the split word and find the index of the user guess against it
		function checkLetter() {
			checkedLetterIndex = individualLetterArray.indexOf(answers.guess);
			console.log(checkedLetterIndex);
		}

		//calling the function
		checkLetter();

		//===INCORRECT GUESS===

		//checking if it the letters match. An index of -1 indicates that the letter was not found
		if (checkedLetterIndex === -1) {

			console.log(chalk.red("\n---------\n" + "INCORRECT!\n" + "---------"));
			console.log("Try again!\n");

			//decrements the number of guesses
			guessesLeft--;
			console.log("Guesses Remaining: " + guessesLeft);

			//if statement to end game when the guesses reach 0
			if (guessesLeft === 0) {

				//logs the following message
				console.log(chalk.bgRed("\n------------------\n" + "    YOU LOSE!     \n" + "------------------\n"));

			}
			
			else {

			//runs the function again, so user can choose another letter
			playGame();

			}
			
		}

		//===CORRECT GUESS===

		else {

			console.log(chalk.green("\n---------\n" + "CORRECT!\n" + "---------"));

			//if the user has guesed the letter already, the letter isn't pushed into the array <BUG>
			if (correctGuesses.indexOf(answers.guess) > -1) {

				//informs user
				console.log("You've guessed this letter already!");
			}

			else {

				//pushing correctly guessed letter into the empty array
				correctGuesses.push(answers.guess);
			};

			//checking if array is being populated
			console.log(correctGuesses);

			//removing the correct letter from the individualLetterArray

			//showing the number of guesses left
			console.log("Guesses remaining: " + guessesLeft);

			//if /else to check whether the user has won <BUG>
			if (correctGuesses.length === individualLetterArray.length) {

				//informs of success
				console.log(chalk.bgGreen("\n------------------\n" + "    YOU WIN!      \n" + "------------------\n"));
			}

			else {

				//runs the function again, so user can choose another letter
				playGame();	
			};

		};
			
	});

}

//this will run the moment the user nodes the file (starts the game)
playGame();


 


