//this is the main file from which the game  is run

//requiring the inquirer and chalk packages
var inquirer = require('inquirer');
var chalk = require('chalk');

//requiring bank.js to get the random word generated by the computer
var computerChoice = require('./bank.js');
// console.log(computerChoice);
//requiring the word
var word = require("./word.js");

//checking if the word gets split
var individualLetterArray = computerChoice.split("");
console.log("TEST array:" + individualLetterArray);


//global variable
var checkedLetterIndex;

// // for loop
// function checkLetter() {
// 	for (var i = 0; i < individualLetterArray.length; i++) {
// 		checkedLetter = individualLetterArray.indexOf(i);
// 		console.log("Checked letter is: " + checkedLetter);
// 	}
// };
// checkLetter();
// console.log(checkedLetter);
// ;

//index of return -1 if not found
// function checkLetter() {
// 	console.log(individualLetterArray.indexOf(answers.guess));
// }
// checkLetter();



function playGame() {

	//prompting the user to select a letter
	inquirer.prompt([
	{
	type: "input",
	name: "guess",
	message: " Guess a letter!"
	},
	]).then(answers => {

	//checking if inquirer and chalk packages function
	// console.log(chalk.cyan(answers.guess + "\n"));

		//for loop for going through each letter in the array
		// for (var i = 0; i < individualLetterArray.length; i++) {

			function checkLetter() {
			checkedLetterIndex = individualLetterArray.indexOf(answers.guess);
			console.log(checkedLetterIndex);
			}


			//checking if it matches
			checkLetter();
			if (checkedLetterIndex === -1) {

				console.log(chalk.red("\n---------\n" + "INCORRECT!\n" + "---------"));
				console.log("Try again!\n");

				//runs the function again, so user can choose another letter
				playGame();
				
			}

			else {

				console.log(chalk.green("\n---------\n" + "CORRECT!\n" + "---------"));

				
			}

		// }
		

	});
}

//this will run the moment the user nodes the file (starts the game)
playGame();


 


